#
# Sample script of using the PSScriptHelper module
#
# Generated by: Matticusau
#
# Generated on: 29/08/2017
#

Import-Module -Name C:\GitHub\PSScriptHelper

Get-ScriptConfig -ScriptPath . -ScriptName 'ConfigurationSample' -ScriptVersion '1.0'

